# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-17 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_captcha', '0002_captcha'),
    ]

    operations = [
        migrations.AddField(
            model_name='captcha',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='captcha',
            name='fresh',
            field=models.BooleanField(default=True),
        ),
    ]
